# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ozioma Ogbe
description: >- # this means to ignore newlines until "baseurl:"
 Hi, I am a Software Engineer and I enjoy solving problems and sharing my solutions,
 I have worked with many technologies but I am more focused on native android application development for now.
  I write primarily about software development and I hope to write about chess and start up in the future

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oziomaogbe.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: oziomajnr
github_username:  oziomajnr
linkedin_username: oziomajnr
stackoverflow_username: ogbe
stackoverflow_number: 3937903
google_analytics: UA-145161693-1
show_excerpts: true
disqus:
    shortname: oziomas-website
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
