name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          cd blog
          echo running gem update --system
          gem update --system
          echo running gem install bundler
          gem install bundler
          echo running bundler update --bundler
          bundler update --bundler
          echo running gem install jekyll bundler
          gem install jekyll bundler
          JEKYLL_ENV=production bundle exec jekyll build --verbose
          cd ..
          ls
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
           GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
