name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master # or master before October 2020

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        run: |
          cd blog
          gem update --system
          gem install bundler
          bundler update --bundler
          gem install jekyll bundler
          JEKYLL_ENV=production bundle exec jekyll build --verbose
          cd ..
          ls
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
